[project]
name = "hello-svc"
version = "0.1.0"
requires-python = "==3.13.*"
dependencies = [
    "fastapi",
    "granian",
    "stamina",
]
[dependency-groups]
dev = [ "fastapi[standard]" , "pytest" ]

[build-system]
requires = ["uv-build"]
build-backend = "uv-build"
